export enum WebSocketMessageTypeEnum {
  TIMER_START = 'timerStart',
  TIMER_REFUSE = 'timerRefuse',
  HAND_RAISE = 'handRaise',
  CONFIRMATION = 'confirmation',
  HEART_RATE = 'heartrate',
  ADD_COOK = 'addCook',
  COOKS_LIST = 'cooksList',
  TASKS_LIST = 'tasksList',
  START_GAME = 'startGame',
  ADD_TIMER = 'addTimer',
  ADD_TASK = 'addTask',
  TABLE_TASK = 'table_task',
  ADD_PRODUCT = 'add_product',
  END_GAME = 'endGame',
  STOP_GAME = 'stop_game',
  RECIPE = 'recipe',
  TASK_PROGRESS = 'taskProgress',
  TASK_FINISHED = 'taskFinished',
}
